sequenceDiagram
    participant SignUp
    participant PersonDAO
    participant Home
    participant CTX
    participant TemplateEngine

    SignUp ->>+ PersonDAO: new PersonDAO()
    SignUp ->>+ PersonDAO: getFromEmailOrUsername()
    PersonDAO -->>- SignUp: Person()

    alt Creation successful
        SignUp -->> Home: redirect
    else Error with Creation
        SignUp ->> CTX: setVariable("error", "...")
        SignUp ->> TemplateEngine: process(ctx, "SignUp.html", ...)
    end

